entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
providers:
  docker:
    exposedByDefault: false
tls:
  certificates:
    - certFile: "/certs/example.com.crt"
      keyFile: "/certs/example.com.key"
