name: Push latest after PR merge
on:
  push:
    branches:
      - master
jobs:
  build:  
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Update apt
        run: sudo apt-get update
      - name: Install tools for generating contracts
        run: sudo apt-get -y install texlive-latex-base texlive-latex-extra texlive-generic-extra lmodern texlive-fonts-recommended ghostscript
      - name: Install pandoc
        run: wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-1-amd64.deb && sudo dpkg -i pandoc-2.13-1-amd64.deb
      - name: Install pip requirements
        run: pip install -r requirements.txt
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: sesamci
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        env:
          DOCKER_BUILD_PUSH: 1                  
          VIRTUAL_ENV: venv
        run: make html && make docker
