name: Build on pull request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Update apt
        run: sudo apt-get update
      - name: Install tools for generating contracts
        run: sudo apt-get -y install texlive-latex-base texlive-latex-extra texlive-plain-generic lmodern texlive-fonts-recommended ghostscript python3-sphinx
      - name: Install pandoc
        run: wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-1-amd64.deb && sudo dpkg -i pandoc-2.13-1-amd64.deb
      - name: Install pip requirements
        run: pip install -r requirements.txt
      - name: Build
        env:
          VIRTUAL_ENV: venv
        run: make html      
